# Generated by Django 4.2.6 on 2023-11-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Name', models.CharField(max_length=200)),
                ('Admin_Email', models.CharField(max_length=200)),
                ('Admin_Phone', models.IntegerField()),
                ('Facility_Name', models.CharField(max_length=200)),
                ('Facility_Address', models.CharField(max_length=200)),
                ('Facility_Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_First_Name', models.CharField(max_length=200)),
                ('Child_Last_Name', models.CharField(max_length=200)),
                ('Child_DoB', models.DateField(max_length=9)),
                ('Child_allergies', models.CharField(max_length=200)),
                ('Parent_First_Name', models.CharField(max_length=200)),
                ('Parent_Last_Name', models.CharField(max_length=200)),
                ('Parent_Phone', models.CharField(max_length=10)),
                ('Parent_Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='child_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sign_In_Date', models.DateField(max_length=9)),
                ('Sign_Out_Date', models.DateField(max_length=9)),
                ('Sign_In_Time', models.TimeField(max_length=30)),
                ('Sign_Out_Time', models.TimeField(max_length=30)),
                ('Facility_Name', models.CharField(max_length=200)),
                ('Child_First_Name', models.CharField(max_length=200)),
                ('Child_Last_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_First_Name', models.CharField(max_length=200)),
                ('Employee_Last_Name', models.CharField(max_length=200)),
                ('Employee_DOB', models.DateField(max_length=9)),
                ('Employee_Address', models.CharField(max_length=200)),
                ('Employee_Phone_Number', models.CharField(max_length=200)),
                ('Classroom', models.CharField(max_length=200)),
                ('Hourly_Salary', models.IntegerField()),
                ('Facility_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_First_Name', models.CharField(max_length=200)),
                ('Child_Last_Name', models.CharField(max_length=200)),
                ('Classroom', models.CharField(max_length=200)),
                ('Tuition_Fee', models.IntegerField()),
                ('Teacher_First_Name', models.CharField(max_length=200)),
                ('Teacher_Last_Name', models.CharField(max_length=200)),
                ('Facility_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility_Name', models.CharField(max_length=200)),
                ('Facility_Address', models.CharField(max_length=200)),
                ('Facility_Phone', models.IntegerField()),
                ('License_Number', models.IntegerField()),
                ('Admin_Name', models.CharField(max_length=200)),
                ('Admin_Email', models.CharField(max_length=200)),
                ('Admin_Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('Parent_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('Parent_First_Name', models.CharField(max_length=200)),
                ('Parent_Last_Name', models.CharField(max_length=200)),
                ('Parent_Phone', models.CharField(max_length=200)),
                ('Child_First_Name', models.CharField(max_length=200)),
                ('Child_Last_Name', models.CharField(max_length=200)),
                ('Child_DOB', models.DateField()),
                ('Child_Allergies', models.CharField(max_length=200)),
                ('Child_Address', models.CharField(max_length=200)),
                ('Sign_In_Date', models.DateField()),
                ('Sign_Out_Date', models.DateField()),
                ('Sign_In_Time', models.TimeField()),
                ('Sign_Out_Time', models.TimeField()),
                ('Facility_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='staff_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sign_In_Date', models.DateField(max_length=9)),
                ('Sign_Out_Date', models.DateField(max_length=9)),
                ('Sign_In_Time', models.TimeField(max_length=30)),
                ('Sign_Out_Time', models.TimeField(max_length=30)),
                ('Facility_Name', models.CharField(max_length=200)),
                ('Teacher_First_Name', models.CharField(max_length=200)),
                ('Teacher_Last_Name', models.CharField(max_length=200)),
                ('Hours_Worked', models.IntegerField()),
                ('Salary_Earned', models.IntegerField()),
            ],
        ),
    ]
