# Generated by Django 4.2.6 on 2023-10-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_First_Name', models.CharField(max_length=200)),
                ('Child_Last_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_First_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='chi',
        ),
    ]
