# Generated by Django 4.2.6 on 2023-11-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_child_consent_box'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin_user',
        ),
    ]
