# Generated by Django 4.2.6 on 2023-10-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_child_employee_delete_chi'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Child_allergies',
            field=models.CharField(default='aler', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='Parent_FullName',
            field=models.CharField(default='10-10-1990', max_length=200),
            preserve_default=False,
        ),
    ]
