# Generated by Django 4.2.6 on 2023-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_child_child_allergies_child_parent_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_DBO',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_Last_Name',
            field=models.CharField(default='unk', max_length=200),
            preserve_default=False,
        ),
    ]
