# Generated by Django 4.2.6 on 2023-11-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_rename_admin_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='Parent_id',
        ),
        migrations.AddField(
            model_name='child',
            name='Parent_Email',
            field=models.CharField(default='err@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_Email',
            field=models.CharField(default='err@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='id',
            field=models.BigAutoField(auto_created=True, default=9999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
