# Generated by Django 4.2.6 on 2023-10-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_employee_employee_dbo_employee_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
