# Generated by Django 4.2.6 on 2023-11-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_employee_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_Phone_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
