# Generated by Django 4.2.6 on 2023-11-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_employee_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_Salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
