# Generated by Django 4.2.6 on 2023-11-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0009_admin_child_attendance_enrollments_facility_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='Child_id',
        ),
        migrations.RemoveField(
            model_name='child',
            name='Consent_Box',
        ),
        migrations.AddField(
            model_name='child',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
